[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geoapps"
version = "0.1.0"
requires-python = ">=3.10.0"
description = "Zadanie -- Budowanie pakietu"
authors = [
    { name = "Martyna Sala", email = "msala983@gmail.com" }
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["docs", "tests"]